export const metadata = {
  title: "Privacy Policy — Coefficient",
  description: "How Coefficient collects, uses, and shares information.",
};

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 space-y-6">
      <h1 className="text-3xl font-bold tracking-tight text-[var(--colors-text-primary)]">
        Privacy Policy
      </h1>
      <p className="text-sm text-[var(--colors-text-secondary)]">
        Last updated: 16 Jul 2026
      </p>

      <p>
        Coefficient (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) provides a
        website and product experiences related to MCP Doctor and related AI
        tooling for platform teams — including MCP scorecards, evals,
        benchmarks, and early-access waitlists (&quot;Services&quot;). This
        Privacy Policy explains how we collect, use, and share information when
        you visit our website or use our Services.
      </p>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          1. Information we collect
        </h2>

        <h3 className="text-lg font-medium text-[var(--colors-text-primary)]">
          A. Information you provide
        </h3>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Contact details:</strong> name, email, company, role (if
            provided) when you join a waitlist, request access, or contact us.
          </li>
          <li>
            <strong>Messages:</strong> content you send via forms, email, or
            support channels.
          </li>
        </ul>

        <h3 className="text-lg font-medium text-[var(--colors-text-primary)]">
          B. Information collected automatically
        </h3>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Usage data:</strong> pages viewed, clicks, referral URLs,
            device/browser type, approximate location (e.g., country/city), and
            timestamps.
          </li>
          <li>
            <strong>Cookies and similar technologies:</strong> used for basic
            site functionality and analytics.
          </li>
        </ul>

        <h3 className="text-lg font-medium text-[var(--colors-text-primary)]">
          C. Product and tooling data (if/when you use the product)
        </h3>
        <p>
          If you use product features (e.g., CLI inspect, eval, or benchmark
          workflows), we may process:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Configuration and telemetry you choose to share:</strong>{" "}
            MCP server names, scorecard results, eval task descriptions, and
            related metadata.
          </li>
          <li>
            <strong>Identifiers:</strong> session or workspace identifiers,
            timestamps, and environment details needed to run or improve the
            Services.
          </li>
          <li>
            <strong>Outputs:</strong> scorecards, suggested fixes, eval
            reports, and benchmark summaries generated by the Services.
          </li>
        </ul>
        <p>
          You control whether you provide this data, and we aim to minimize
          collection to what is necessary to deliver the Services.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          2. How we use information
        </h2>
        <p>We use information to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Provide, operate, and improve the Services.</li>
          <li>Respond to requests, inquiries, and support issues.</li>
          <li>
            Manage waitlists and send product-access or early-access emails you
            request.
          </li>
          <li>
            Analyze product performance and usage (e.g., improve UX,
            reliability, and MCP scorecard quality).
          </li>
          <li>Maintain security, prevent abuse, and troubleshoot issues.</li>
          <li>
            Communicate updates, product access, and relevant information you
            request.
          </li>
          <li>Comply with legal obligations.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          3. Legal bases (UK)
        </h2>
        <p>
          Where applicable, we process personal data under these bases:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Consent (e.g., marketing or waitlist opt-in).</li>
          <li>Contract (to provide Services you request).</li>
          <li>
            Legitimate interests (e.g., security, analytics, product
            improvement).
          </li>
          <li>Legal obligation (where required).</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          4. How we share information
        </h2>
        <p>We do not sell your personal information.</p>
        <p>We may share information with:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Service providers:</strong> hosting, analytics, email,
            customer support, database, and infrastructure vendors that process
            data on our behalf.
          </li>
          <li>
            <strong>AI/ML providers</strong> (if you use AI-powered features
            such as evals): to analyze content and generate scorecards, fixes,
            or reports.
          </li>
          <li>
            <strong>Legal and safety:</strong> if required to comply with law,
            enforce our terms, or protect rights and safety.
          </li>
          <li>
            <strong>Business transfers:</strong> in connection with mergers,
            acquisitions, financing, or sale of assets.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          5. Data retention
        </h2>
        <p>
          We retain data only as long as necessary for the purposes described
          above, unless a longer retention period is required or permitted by
          law.
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Website and waitlist submissions:</strong> retained for a
            reasonable period to manage communications and early access.
          </li>
          <li>
            <strong>Product outputs and telemetry</strong> (if applicable):
            retained according to workspace settings or contractual agreement,
            and deleted upon request where feasible.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          6. Security
        </h2>
        <p>
          We use reasonable administrative, technical, and organizational
          measures designed to protect information. No system is 100% secure;
          you use the Services at your own risk.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          7. Your choices and rights
        </h2>
        <p>
          Depending on your location, you may have rights to:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Access, correct, or delete your personal data.</li>
          <li>Object to or restrict certain processing.</li>
          <li>Withdraw consent (where processing is based on consent).</li>
          <li>Request portability of certain data.</li>
        </ul>
        <p>
          To exercise rights, contact us at:{" "}
          <strong>
            <a href="mailto:hello@coefficient.work" className="underline hover:no-underline">
              hello@coefficient.work
            </a>
          </strong>
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          8. International transfers
        </h2>
        <p>
          If we transfer personal data internationally, we take steps designed
          to ensure appropriate safeguards are in place (e.g., contractual
          protections).
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          9. Children
        </h2>
        <p>
          The Services are not intended for children under 13 (or the minimum
          age required in your jurisdiction). We do not knowingly collect
          personal information from children.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          10. Cookies
        </h2>
        <p>We may use cookies for:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Essential site functionality</li>
          <li>Analytics and performance</li>
        </ul>
        <p>You can control cookies through your browser settings.</p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          11. Changes to this policy
        </h2>
        <p>
          We may update this Privacy Policy from time to time. We&apos;ll
          update the &quot;Last updated&quot; date and post the revised version.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-semibold text-[var(--colors-text-primary)]">
          12. Contact
        </h2>
        <p>
          Coefficient
          <br />
          Email:{" "}
          <strong>
            <a href="mailto:hello@coefficient.work" className="underline hover:no-underline">
              hello@coefficient.work
            </a>
          </strong>
        </p>
      </section>
    </main>
  );
}
